apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: resmed-services
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - production
  selector:
    matchLabels: {}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
