run:
  timeout: 5m
  go: "1.26"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - noctx
    - bodyclose

linters-settings:
  goimports:
    local-prefixes: github.com/taotao19950405/resmed-platform-dashboard

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
