apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: patient-service
  description: Patient records and CPAP device assignments
  annotations:
    github.com/project-slug: taotao19950405/resmed-platform-dashboard
  links:
    - url: http://localhost:8083/health
      title: Health
    - url: http://localhost:8083/metrics
      title: Metrics
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: resmed-platform
